sudo: false
dist: trusty
language: java
install:
  - mkdir -p ${HOME}
  - cd ${HOME}
  - wget https://download.java.net/java/early_access/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz
  - tar -xzf openjdk-11+28_linux-x64_bin.tar.gz
  - export JAVA_HOME=${HOME}/jdk-11
  - export PATH=${JAVA_HOME}/bin:${PATH}
  - java -version
  - cd -
script:
  - ./gradlew clean check
